---
- name: Install Main Repository
  apt_repository: repo='{{ item }}' update_cache=yes
  with_items:
    - deb http://packages.dotdeb.org wheezy all
    - deb-src http://packages.dotdeb.org wheezy all

- name: Install PHP 5.5 repository
  apt_repository: repo='{{ item }}' update_cache=yes
  with_items:
    - deb http://packages.dotdeb.org wheezy-php55 all
    - deb-src http://packages.dotdeb.org wheezy-php55 all

- name: Install Dotdeb Key
  apt_key: url=http://www.dotdeb.org/dotdeb.gpg

- name: Upgrade system
  apt: upgrade=dist update_cache=yes force=yes
