---
- name: Install nginx
  apt: name=nginx state=latest

- name: Copy nginx configuration
  template: src=wrappmsg.conf.j2 dest=/etc/nginx/sites-enabled/wrappmsg.conf
  notify: restart nginx

- name: Restart nginx
  service: name=nginx enabled=yes
